version: '3.1'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: bacen_db
    volumes:
      - data/bacen/
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'